---
title: "Tijd_grafieken"
author: "Bas"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
library(readr)
library(here)
library(tidyverse)
library(dplyr)
library(plotly)
library(gridExtra)
#install.packages("plotly")
#install.packages("gridExtra")
```

```{r}
data_time <- read_csv(here("data", "data.csv"))
```

```{r}

#A function for calling graphs based on genotype and session
#data = the data that is to be used
#column = The colum for the data you want on the y-axis
#title = the title of the graph, should be in ""
#y_as = how the y_axis is called
time_graph <- function(data, column, title, y_as){
  
  #Make new data set of "ruwe-data"
  duration_data <- data

  #Calculate the average duration per session and genotype
  duration_genotype_session <- duration_data %>% group_by(Session, genotype) %>% summarize(mean_duration=mean(!!column), stdev=sd(!!column))

  #Load a bar_graph
  graph <- duration_genotype_session %>%
    ggplot(aes(x = duration_genotype_session$Session, y = duration_genotype_session$mean_duration, fill = duration_genotype_session$genotype)) + 
    geom_bar(stat = "identity", position= "dodge") +
    geom_errorbar(aes(x=Session, ymin=mean_duration-stdev, ymax=mean_duration+stdev), width=.2,position=position_dodge(0.9), size=0.5) +
    theme_minimal() +
    labs(title = title,
        x = "Session",
        y = y_as,
        fill = "Genotype")
    #geom_vline(xintercept = 10, colour = "red")      # Een line waar de bekinjecellen niet meer werken
    
  ggplotly(graph)
}


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#Change the colum of "Date Acquried" and "Birth Date" to be a date class instead of character
data_time$`Date Acquired` <- as.Date(data_time$`Date Acquired`, tryFormats = c("%d-%m-%Y"))
data_time$`Birth Date` <- as.Date(data_time$`Birth Date`, tryFormats = c("%d-%m-%Y"))

#Calculate the age per mice
data_time$age_days <- as.numeric(difftime(data_time$`Date Acquired`, data_time$`Birth Date`))

# Graph for Average age of mice per session per genotype
time_graph(data_time, column = quo(age_days), "Average age of mice per session per genotype", "Age in days)")

#call a 5 number summary
knitr::kable(data.frame(data = c("minimum", "lower-hinge", "median", "upper-hinge", "maximum"),  duration = fivenum(data_time$age_days)), caption = "5 number summary, duration in days")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Graph for Average trail duration per session per genotype
time_graph(data_time, column = quo(`Trial duration(s)`), "Average trail duration per session per genotype", "Duration (s)")

#call a 5 number summary
knitr::kable(data.frame(data = c("minimum", "lower-hinge", "median", "upper-hinge", "maximum"),  duration = fivenum(data_time$`Trial duration(s)`)), caption = "5 number summary, duration in seconds")

# Graph for Average resting duration per session per genotype
time_graph(data_time, column = quo(`Resting(ms)`), "Average resting duration per session per genotype", "Resting Duration (ms)")

#call a 5 number summary
knitr::kable(data.frame(data = c("minimum", "lower-hinge", "median", "upper-hinge", "maximum"),  duration = fivenum(data_time$`Resting(ms)`)), caption = "5 number summary, duration in seconds")

# Graph for Duration for the mice to be on the ladder after cue
time_graph(data_time, column = quo(`On Ladder After Cue(ms)`), "Duration for the mice to be on the ladder after cue", "Duration (ms)")

#call a 5 number summary
knitr::kable(data.frame(data = c("minimum", "lower-hinge", "median", "upper-hinge", "maximum"),  duration = fivenum(data_time$`On Ladder After Cue(ms)`)), caption = "5 number summary, duration in seconds")
```


