---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# graphify

<!-- badges: start -->
<!-- badges: end -->

The goal of graphify is to make a few graphs for an erasmusladder project.

## Installation

You can install the development version of graphify from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("bburg2/graphify")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(graphify)
library(readr)
library(here)
library(tidyverse)
library(dplyr)
library(plotly)

# load in some data
## data_time <- read_csv(here("data", "data.csv"))

# Graph for Average trail duration per session per genotype
## time_graph(data_time, column = quo(`Trial duration(s)`), "Average trail duration per session per genotype", "Duration (s)")

```

